_BASE_: "../Base-RCNN-FPN-4gpu.yaml"
MODEL:
  WEIGHTS: "./pretrained_model/output_3x_finetune_r101.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
    DEFORM_ON_PER_STAGE: [False, True, True, True] # on Res3,Res4,Res5
    DEFORM_MODULATED: False
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
