_BASE_: "../Base-RCNN-FPN-4gpu.yaml"
MODEL:
  WEIGHTS: "./model_final_a3ec72.pkl"
  #WEIGHTS: "./output_3x_finetune_101/model_final.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
