_BASE_: "../Base-RCNN-FPN-4gpu.yaml"
MODEL:
  WEIGHTS: "./model_final_a3ec72.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
DATASETS:
  TEST: ("lvis_v0.5_val_cocofied",)

